### ISSUE TITLE
I can't run example in readme

### ISSUE THREAD

**Issue by hesidoryn** [cyclejs-community/cyclic-router#129]
I'm a beginner in cyclejs( in nodejs too). And i can't run example in readme. I installed all nedded packages, but i see an error "makeHistoryDriver throws error for a proper history object...". Can you correct example in readme and explain me why this error causes? Sorry for maybe dumb question.

**Comment by andreloureiro** [comment]
@HeorhiSidorin maybe you have `history@4.x.x` in your dependencies. If that's the case, downgrading it to version 3.2.1 should fix this error.

**Comment by Malusovium** [comment]
#190 Will fix this problem by correcting the readme. So one can use the latest history package: `history@4.x.x`.

like so:
```
import { createBrowserHistory } from 'history' 

router: makeRouterDriver(createBrowserHistory(), switchPath) 
```

**Comment by ntilwalli** [comment]
I merged the README PR referenced above.
