### ISSUE TITLE
TypeScript warnings

### ISSUE THREAD

**Issue by ricochet1k** [cyclejs-community/cyclic-router#139]
When using Typescript with webpack, I get a several warnings from cyclic-router like this:

```
WARNING in ./~/cyclic-router/lib/index.js
Cannot find source file '../src/index.ts': Error: Cannot resolve 'file' or 'directory' ../src/index.ts in /web-cycle/node_modules/cyclic-router/lib
```

Can you include the typescript files in the npm package?

**Comment by TylorS** [comment]
They are distributed via NPM

https://github.com/cyclejs-community/cyclic-router/blob/master/package.json#L6

If you could provide more information perhaps it'd be easier to know how to help

**Comment by ricochet1k** [comment]
Source maps in webpack seem to want the original src/ files, which are being ignored by your .npmignore.

Some examples: 
- http://stackoverflow.com/questions/36111827/webpack-angular2-cannot-find-ts-files-from-widget-library - discussion about including .ts files in comments, not answer
- https://github.com/dzonatan/angular2-linky/issues/5 fix here: https://github.com/dzonatan/angular2-linky/commit/cf2ebf7067451104573ae880a321a16ceeff72a3

**Comment by ricochet1k** [comment]
Thanks for looking into this by the way.

**Comment by TylorS** [comment]
Okay, I'll remove the src/ directory from the .npmignore later tonight

**Comment by kylecordes** [comment]
I think this is fixed and can be closed.
