### ISSUE TITLE
Support redirects?

### ISSUE THREAD

**Issue by alisd23** [cyclejs-community/cyclic-router#16]
Would be nice to support redirecting, for example `my/url` to `my/url/specific`.
Don't think it's possible to signal this with switch-path, so would probably have to be at a higher level than that, possibly an option when defining routes?

**Comment by TylorS** [comment]
I'm not sure I follow what you're asking. Do you have a situation where you are not able to programmatically push the new path to the router?

**Comment by alisd23** [comment]
There's a case if the user tries to directly go to some url that doesn't exist in the browser (and there's no specific routing setup on the server), when the client initially loads it will try to go to that route and will not match anything. In that case you might want to be able to redirect routes to one that exists, like the example i mentioned above, ideally in the same routes object which switch-path uses. 

In my case I can actually do the redirect with specific server-side routes, but you don't necessarily need specific server side routes. Does that make sense?

**Comment by TylorS** [comment]
Are you server-side rendering of the cycle.js application itself?

**Comment by TylorS** [comment]
You're able to a "Not found" route if nothing is matched

```js
const routes = {
  '/my/url/specific': Component,
  '*': NotFoundComponent
}
```

From the NotFoundComponent you could place logic which would handle redirects

**Comment by TylorS** [comment]
I'm going to close this as it's gotten stale, but please reopen if you still find this to be an issue.
