### ISSUE TITLE
Problem running example code

### ISSUE THREAD

**Issue by nikoskalogridis** [cyclejs-community/cyclic-router#169]
I am trying to use cyclic-router and it seems that when a new route event occurs its followed by the default one
```javascript
function main(sources) {
  const match$ = sources.router.define({
    '/': HomeComponent,
    '/other': OtherComponent
  });

  const page$ = match$.debug().map(({path, value}) => {
    return value(Object.assign({}, sources, {
      router: sources.router.path(path)
    }));
  });

  return {
    DOM: page$.map(c => c.DOM).flatten(),
    router: xs.of('/'),
  };
}
```
Running this example when I enter the url /other the match$ receives 2 events: The first one is a POP event with the path /other and then a "/" event follows. Am I missing something here?

the object in the first event is a `{location: {action: "POP",...}, path: "/other"}` then the second event object is `{location: {action: "PUSH"}, path: "/"}`

**Comment by FeliciousX** [comment]
hey @nikoskalogridis, it seems like your `main` function returns the `router` sinks as `xs.of( '/' )`

that might cause the problem..

you should be doing something like

```javascript
return {
  DOM: page$.map( c => c.DOM ).flatten(),
  router: page$.map( c => c.router ).flatten()
};
```

**Comment by FeliciousX** [comment]
to explain your problem

no matter which component your router loads, the route will be back to the `xs.of( '/' )`

even removing it entirely would work too right now

**Comment by nikoskalogridis** [comment]
@FeliciousX thanks a lot for your help. I actually found that moments before I quit and went to bed last night :-) Yes you are right the `xs.of("/")` was the problem. Wished the readme example was including some text about that. It took me almost two days to figure out.

**Comment by nikoskalogridis** [comment]
Actually removing the router property entirely would not work. In my case this made the trick `page$.map((c) => c.router || xs.never()).flatten()` so even if a component does not provide a sink the rest of the components would be able to have access to the router.

Shall I open a PR for including this in the readme of the project. I think it would help other beginners like myself

**Comment by FeliciousX** [comment]
sure thing! Open a PR and i think @TylorS  will review it :)

**Comment by TylorS** [comment]
Hello @nikoskalogridis, yes in a real application I also us `c.router || never()` as you mention. PR definitely welcomed.

Thanks for all that you help with @FeliciousX :D

**Comment by leefsmp** [comment]
Kinda confusing that your "basic usage" example is not working out of the box. Thanks for comments.
