### ISSUE TITLE
Maintainers and Contributors wanted

### ISSUE THREAD

**Issue by wyqydsyq** [cyclejs-community/cyclic-router#183]

**Comment by TylorS** [comment]
Yeah truth be told I don't have much time for Cycle these days. I'd love to see someone take this project up. I'd be very willing to hand permission to those, hopefully multiple, people willing to update and help maintain this library.

**Comment by mightyiam** [comment]
I can do my best.

**Comment by ntilwalli** [comment]
You could add me since I use the lib and maintain it for my own purposes already...

**Comment by TylorS** [comment]
I sent you an invite to be an admin here @ntilwalli. Also added you to be able to publish to npm.
