### ISSUE TITLE
After a while the router becomes too slow - rxjs

### ISSUE THREAD

**Issue by nicolocodev** [cyclejs-community/cyclic-router#188]
Hi folks! 
I'm using cyclic-router on a cycle/rxjs app. The router is working, but, after some clicks (navigation) this becomes too slow, I mean, im not doing anything else but clicking the `a` tags i've added.

I created [this sample repo](https://github.com/nicolocodev/cycletestapp/) to repro the issue: clone, `npm install` -> `npm start` -> navigate between the two pages -> checkout how this become "slow"

am i missing something?

**Comment by TylorS** [comment]
I haven't tested in myself, but I'd try using `switchMap` instead of `flatMap` as a preliminary attempt. `flatMap` will keep subscriptions forever, whereas `switchMap` will only keep the most recent, which in the case of routing is generally what you want.
