### ISSUE TITLE
export RouteMatcherReturn interface

### ISSUE THREAD

**Issue by kylecordes** [cyclejs-community/cyclic-router#193]
To fully type an application using cyclic-router, I need to refer to the RouteMatcherReturn interface. 

```
export interface RouteMatcherReturn {
    path: string;
    value: any;
}
```

This currently requires ugly imports:

```
import { RouteMatcherReturn } from 'cyclic-router/lib/interfaces';
```

I think this interface should be re-export this from the facade, for simpler use from application code.

(Related: RouterSource.define currently returns type any - it's really a `Stream<RouteMatcherReturn>`, right?)

**Comment by ntilwalli** [comment]
Can you submit a PR?

**Comment by kylecordes** [comment]
Yes... But I feel like I should use this router a bit more, to have confidence my changes are good. Will do.

**Comment by kylecordes** [comment]
@ntilwalli #194
