### ISSUE TITLE
How to replace a route?

### ISSUE THREAD

**Issue by IdanLoo** [cyclejs-community/cyclic-router#199]
just replace, not push.

**Comment by ntilwalli** [comment]
You should look at '@cycle/history' for the documentation.  Under the hood this router uses https://github.com/ReactTraining/react-router.

In this case you would send:
```
{
  type: 'replace',
  pathname: '/some/path/here'
}
```

**Comment by IdanLoo** [comment]
@ntilwalli thx

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Samsung SM-G9500 发送_
