### ISSUE TITLE
Add prettier to repo

### ISSUE THREAD

**Issue by jvanbruegge** [cyclejs-community/cyclic-router#202]
Makes formatting easier, as everyone uses a different style.
Simply run `npm run format` and the code is formatted correctly

I can set that up if I know what your preferences are

**Comment by jvanbruegge** [comment]
E.g. I use 
- 4 spaces
- semicolons
- space inside bracets when destructuring
- single quotemark strings

**Comment by ntilwalli** [comment]
Does it enforce rules like linting?

**Comment by jvanbruegge** [comment]
No, it's just formatting, but automatic without you having to fix linting rules, so it's best to have both (linter for stuff like `unused-vars` and prettier for formatting)

**Comment by ntilwalli** [comment]
sounds good

**Comment by jvanbruegge** [comment]
which style? I can open a PR then

**Comment by ntilwalli** [comment]
I amended my comment above, your prefs are fine

**Comment by jvanbruegge** [comment]
I didn't see that one yet :)
