### ISSUE TITLE
Can't match path correctly !

### ISSUE THREAD

**Issue by IdanLoo** [cyclejs-community/cyclic-router#210]
I have a router defined as

```Javascript
const match$ = sources.router.define({
  '/a': AComponent,
  '/aa': AAComponent,
  '/ca': CAComponent
}
```

This stream will be `{path: null, value: null}` when path is `/aa`. But it works when path is `/ca`.

**Comment by jvanbruegge** [comment]
This is most likely a bug in switch-path
