### ISSUE TITLE
Uncaught TypeError: runSA.remember is not a function

### ISSUE THREAD

**Issue by anurtayev** [cyclejs-community/cyclic-router#58]
While trying open an application I get following error message in browser console:

makeHistoryDriver.js:42 Uncaught TypeError: runSA.remember is not a function
historyDriver                 @ makeHistoryDriver.js:42
routerDriver                  @ makeRouterDriver.js:24
callDrivers                    @ index.js:21
Cycle                            @ index.js:73
run                               @ index.js:61
(anonymous function) @ app.js:33
(anonymous function) @ bundle.js:1042
**webpack_require** @ bundle.js:556
fn                                 @ bundle.js:87
(anonymous function) @ multi_main:3
(anonymous function) @ bundle.js:586
**webpack_require** @ bundle.js:556
(anonymous function) @ bundle.js:579
(anonymous function) @ bundle.js:582

running on Windows. Any suggestions what this might be?

**Comment by TylorS** [comment]
You'll need to update to the newest version of `@cycle/*-run` `@cycle/*-adapter`. I believe remember() was added in v3.x.x of the each package.
